cor.test(bank$cons.price.idx, bank$cons.cof.idx, method = "pearson")
bank$education = as.numeric(bank$education)
bank$default = as.numeric(bank$default)
which(bank$emp.var.rate==1.1)
consumer<- bank$age
str(bank)
summary(bank)
bank$job = as.numeric(bank$job)
hist(bank$job, xlab = "job", ylab = "frequency", main = "distribution of client based on job", col = "red")
cor.test(bank$job, bank$martial)
cor.test(bank$job, bank$education, method = "pearson")
bank$education = as.numeric(bank$education)
cor.test(bank$job, bank$education, method = "pearson")
bank$martial = as.numeric(bank$marital)
cor.test(bank$job, bank$martial, method = "pearson")
bank$education = as.numeric(bank$education)
cor.test(bank$job, bank$education, method = "pearson")
bank$default = as.numeric(bank$default)
cor.test(bank$job, bank$default, method = "pearson")